from __future__ import annotations

from datetime import datetime


def generate_pr_title(scan_id: int, fix_count: int, auto_count: int) -> str:
    return f"fix: site-inspector auto-fixes ({fix_count} fixes, {auto_count} auto)"


def generate_pr_body(fixes: list[dict], scan_id: int,
                     target_name: str) -> str:
    """Generate a structured PR description from fix summaries."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    auto_fixes = [f for f in fixes if f.get("fix_type") == "fully_auto"]
    semi_fixes = [f for f in fixes if f.get("fix_type") == "semi_auto"]

    lines = [
        "## Summary",
        f"Automated fixes generated by Site Inspector for **{target_name}** (scan #{scan_id})",
        f"- **{len(auto_fixes)}** fully-automated fixes (safe to merge)",
        f"- **{len(semi_fixes)}** semi-automated fixes (review required)",
        "",
        "## Auto-Fixes (No Review Required)",
    ]

    for f in auto_fixes:
        lines.append(f"- **{f.get('category', '')}**: {f.get('description', '')[:120]} "
                     f"on `{f.get('url', '')}`")

    if semi_fixes:
        lines.append("")
        lines.append("## Semi-Auto Fixes (Please Review)")
        for f in semi_fixes:
            lines.append(f"- **{f.get('category', '')}**: {f.get('description', '')[:120]} "
                         f"on `{f.get('url', '')}`")
            if f.get("diff"):
                lines.append(f"  ```diff\n  {f['diff'][:500]}\n  ```")

    lines += [
        "",
        "## Verification",
        f"After merging, metrics will be tracked for 14 days. "
        f"If any metric degrades by more than 10%, an automatic rollback will be triggered.",
        "",
        f"Generated at {now}",
        "Site Inspector",
    ]

    return "\n".join(lines)
