from __future__ import annotations

import asyncio
import logging
from datetime import datetime
from pathlib import Path

from config.settings import Settings

logger = logging.getLogger(__name__)


class GitWorkflow:
    """Manage the fix → branch → commit → PR pipeline."""

    def __init__(self, settings: Settings, repo_path: Path):
        self.settings = settings
        self.repo_path = repo_path
        self.author_name = settings.git_author_name
        self.author_email = settings.git_author_email
        self.platform = settings.git_platform

    async def _run_git(self, *args: str) -> str:
        """Run a git command and return stdout."""
        cmd = ["git", "-C", str(self.repo_path)] + list(args)
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode != 0:
            raise RuntimeError(f"git {' '.join(args)} failed: {stderr.decode()}")
        return stdout.decode().strip()

    async def is_git_repo(self) -> bool:
        """Check if the path is a valid git repository."""
        try:
            await self._run_git("rev-parse", "--git-dir")
            return True
        except Exception:
            return False

    async def ensure_clean(self) -> bool:
        """Check if working tree is clean."""
        try:
            status = await self._run_git("status", "--porcelain")
            return status == ""
        except Exception:
            return True

    async def create_fix_branch(self, scan_id: int) -> str:
        """Create a new branch for fixes."""
        branch_name = f"fix/site-inspector-scan-{scan_id}-{datetime.now():%Y%m%d-%H%M}"
        await self._run_git("checkout", "-b", branch_name)
        logger.info(f"Created branch: {branch_name}")
        return branch_name

    async def stage_and_commit(self, files: list[str], message: str) -> str:
        """Stage specific files and commit with message."""
        if not files:
            return ""

        # Configure author for this commit
        await self._run_git("config", "user.name", self.author_name)
        await self._run_git("config", "user.email", self.author_email)

        for f in files:
            await self._run_git("add", f)

        # Escape message for command line
        commit_msg = f"{message}\n\nAuto-generated by Site Inspector"
        await self._run_git("commit", "-m", commit_msg)

        commit_hash = await self._run_git("rev-parse", "HEAD")
        logger.info(f"Committed {len(files)} files: {commit_hash[:8]}")
        return commit_hash[:8]

    async def push_branch(self, branch: str) -> bool:
        """Push the branch to remote."""
        try:
            await self._run_git("push", "-u", "origin", branch)
            return True
        except Exception as e:
            logger.error(f"Failed to push branch {branch}: {e}")
            return False

    async def create_pr(self, branch: str, title: str, body: str) -> str | None:
        """Create a pull request via gh CLI.

        Runs gh inside the target repo (cwd) so it auto-detects the repository.
        For forks, resolves the remote so --head uses the correct owner:branch format.
        Auto-detects the default branch from the remote.
        """
        try:
            import shutil
            if not shutil.which("gh"):
                logger.warning("GitHub CLI (gh) not available, skipping PR creation")
                return None

            # Resolve remote info so --head works for forks
            head_ref = branch
            try:
                push_remote = await self._run_git(
                    "remote", "get-url", "--push", "origin",
                )
                # Extract owner from remote URL (handles both https:// and git@ formats)
                import re
                m = re.match(
                    r"(?:https://[^/]+/|git@[^:]+:)([^/]+)/",
                    push_remote,
                )
                if m:
                    head_ref = f"{m.group(1)}:{branch}"
                    logger.info(f"Resolved fork head: {head_ref}")
            except Exception:
                pass  # fall back to bare branch name

            # Auto-detect default branch from remote
            base_branch = self.settings.git_default_branch
            try:
                head_ref_result = await self._run_git(
                    "symbolic-ref", "refs/remotes/origin/HEAD",
                )
                # Output: refs/remotes/origin/master → extract "master"
                base_branch = head_ref_result.strip().split("/")[-1]
                logger.info(f"Detected default branch: {base_branch}")
            except Exception:
                base_branch = base_branch or "main"
                logger.info(f"Could not detect default branch, using: {base_branch}")

            # Check gh auth status first (early warning)
            auth_proc = await asyncio.create_subprocess_exec(
                "gh", "auth", "status",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            await auth_proc.communicate()
            if auth_proc.returncode != 0:
                logger.warning(
                    "gh not authenticated — PR cannot be created. "
                    "Run 'gh auth login' in the terminal."
                )
                return None

            # Extract repo slug from git remote for REST API
            repo_slug = ""
            try:
                remote_url = await self._run_git("remote", "get-url", "origin")
                import re
                m = re.match(
                    r"(?:https://github\.com/|git@github\.com:)([^/]+/[^/]+?)(?:\.git)?$",
                    remote_url.strip(),
                )
                if m:
                    repo_slug = m.group(1)
            except Exception:
                pass

            if not repo_slug:
                logger.warning("Could not determine repo slug, falling back to gh pr create")
                proc = await asyncio.create_subprocess_exec(
                    "gh", "pr", "create",
                    "--title", title, "--body", body,
                    "--base", base_branch, "--head", head_ref,
                    stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
                    cwd=str(self.repo_path),
                )
                stdout, stderr = await proc.communicate()
                if proc.returncode == 0:
                    return stdout.decode().strip()
                return None

            # Use REST API with retry (avoids GraphQL TLS timeout, handles network jitter)
            for attempt in range(3):
                if attempt > 0:
                    wait = 2 ** attempt
                    logger.info(f"PR create retry {attempt + 1}/3 after {wait}s...")
                    await asyncio.sleep(wait)

                logger.info(
                    f"Creating PR via REST API (attempt {attempt + 1}): "
                    f"{repo_slug} head={head_ref} base={base_branch}"
                )
                proc = await asyncio.create_subprocess_exec(
                    "gh", "api", f"repos/{repo_slug}/pulls",
                    "-f", f"title={title}",
                    "-f", f"head={head_ref}",
                    "-f", f"base={base_branch}",
                    "-f", f"body={body}",
                    "--jq", ".html_url",
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                stdout, stderr = await proc.communicate()
                stderr_text = stderr.decode().strip()

                if proc.returncode == 0:
                    pr_url = stdout.decode().strip()
                    logger.info(f"PR created: {pr_url}")
                    return pr_url

                if "TLS handshake timeout" in stderr_text or "timeout" in stderr_text.lower():
                    logger.warning(f"PR create timeout (attempt {attempt + 1}/3), retrying...")
                    continue
                else:
                    # Non-timeout error, don't retry
                    break

            logger.warning(f"gh api PR create failed after retries: {stderr_text}")
            return None
        except FileNotFoundError:
            logger.warning("gh CLI not found on PATH")
            return None
        except Exception as e:
            logger.error(f"Failed to create PR: {e}")
            return None

    async def merge_pr(self, pr_url: str) -> bool:
        """Auto-merge a PR if CI passes."""
        try:
            import shutil
            if shutil.which("gh"):
                proc = await asyncio.create_subprocess_exec(
                    "gh", "pr", "merge", pr_url, "--auto", "--squash",
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                stdout, stderr = await proc.communicate()
                return proc.returncode == 0
        except Exception as e:
            logger.error(f"Failed to merge PR {pr_url}: {e}")
        return False

    async def revert_commit(self, commit_hash: str) -> str | None:
        """Revert a specific commit (for rollback)."""
        try:
            await self._run_git("revert", commit_hash, "--no-edit")
            rollback_hash = await self._run_git("rev-parse", "HEAD")
            await self._run_git("push", "origin", "HEAD")
            logger.info(f"Reverted commit {commit_hash[:8]} as {rollback_hash[:8]}")
            return rollback_hash[:8]
        except Exception as e:
            logger.error(f"Failed to revert {commit_hash}: {e}")
            return None
