from __future__ import annotations

from datetime import datetime, timedelta
from pathlib import Path
from typing import Sequence

from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from src.storage.models import Fix, Issue, Scan


class WeeklyReportGenerator:
    """Generate weekly trend report with aggregated data."""

    def __init__(self, session: AsyncSession, output_dir: Path):
        self.session = session
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    async def generate(self, target_name: str,
                       target_id: int) -> Path:
        """Generate weekly HTML report. Returns file path."""
        week_ago = datetime.utcnow() - timedelta(days=7)

        # Fetch scans from last 7 days
        result = await self.session.execute(
            select(Scan)
            .where(
                Scan.target_id == target_id,
                Scan.started_at >= week_ago,
                Scan.status.in_(("completed", "degraded")),
            )
            .order_by(Scan.started_at)
        )
        scans = list(result.scalars().all())

        # Aggregate issues
        total_issues = sum(s.total_issues_found for s in scans)
        total_pages = sum(s.pages_crawled for s in scans)

        # Count fixes
        result = await self.session.execute(
            select(func.count(Fix.id)).where(
                Fix.scan_id.in_([s.id for s in scans]),
                Fix.status == "applied",
            )
        )
        total_fixes = result.scalar() or 0

        # Generate HTML
        from jinja2 import Template

        template = Template("""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Weekly Report - {{ target_name }}</title>
<style>
    body { font-family: -apple-system, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; }
    h1 { color: #16213e; }
    .summary { display: flex; gap: 20px; margin: 20px 0; }
    .stat { padding: 20px; background: #f1f3f5; border-radius: 8px; text-align: center; flex: 1; }
    .stat-value { font-size: 28px; font-weight: bold; color: #0f3460; }
    .stat-label { font-size: 12px; color: #868e96; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { padding: 8px; border-bottom: 1px solid #dee2e6; text-align: left; }
    th { background: #f1f3f5; }
</style></head>
<body>
    <h1>Weekly Inspection Report</h1>
    <p><strong>{{ target_name }}</strong> — {{ week_start }} to {{ week_end }}</p>

    <div class="summary">
        <div class="stat"><div class="stat-value">{{ scans|length }}</div><div class="stat-label">Scans</div></div>
        <div class="stat"><div class="stat-value">{{ total_pages }}</div><div class="stat-label">Pages Checked</div></div>
        <div class="stat"><div class="stat-value">{{ total_issues }}</div><div class="stat-label">Issues Found</div></div>
        <div class="stat"><div class="stat-value">{{ total_fixes }}</div><div class="stat-label">Fixes Applied</div></div>
    </div>

    <h2>Daily Trend</h2>
    <table>
        <tr><th>Date</th><th>Type</th><th>Pages</th><th>Issues</th><th>Status</th></tr>
        {% for scan in scans %}
        <tr>
            <td>{{ scan.started_at.strftime('%Y-%m-%d') }}</td>
            <td>{{ scan.scan_type }}</td>
            <td>{{ scan.pages_crawled }}</td>
            <td>{{ scan.total_issues_found }}</td>
            <td>{{ scan.status }}</td>
        </tr>
        {% endfor %}
    </table>

    <p style="font-size:12px;color:#868e96;margin-top:30px;">
        Generated by Site Inspector at {{ generated_at }}
    </p>
</body></html>""")

        html = template.render(
            target_name=target_name,
            week_start=week_ago.strftime("%Y-%m-%d"),
            week_end=datetime.utcnow().strftime("%Y-%m-%d"),
            scans=scans,
            total_pages=total_pages,
            total_issues=total_issues,
            total_fixes=total_fixes,
            generated_at=datetime.utcnow().isoformat(),
        )

        filename = f"weekly-report-{datetime.utcnow():%Y%m%d}.html"
        filepath = self.output_dir / filename
        filepath.write_text(html, encoding="utf-8")
        return filepath
